### ISSUE TITLE
Cant Load File on GODOT3.2.3

### ISSUE THREAD

**Issue by titangamingglt** [EXPWorlds/Godot-Dialog-System#5]
Save Dialog File is not loading on godot3.2.3

**Comment by EXPWorlds** [comment]
Works for me. Make sure you're not trying to load a "Baked" Story File. If that isn't the problem, give me more detail about the behavior/error messages, and we'll see what we can do. Either way, let me know.

**Comment by EXPWorlds** [comment]
I'm gonna close this issue. If you're still having problems feel free to email me.
